#include<stdio.h>
int sum(int ph[])
{
    int i,j,k,l,count=0,sum=0,sum1=0,sum2=0,max=0,sum21,sum22,sum23,sum24;
    for(i=0;i<4;i++)
    {
        if(ph[i]/10==1||ph[i]/10==14)
        {
            count++;
        }
        else
        {
            if(ph[i]/10>10)
            {
                sum1=sum1+10;
            }
            else
            {
                sum1=sum1+ph[i]/10;
            }
        }
    }
    if(count==1)
    {

        for(i=0;i<2;i++)
        {
            sum2=0;
            if(i==0)
            {
                sum2=sum2+1;
            }
            if(i==1)
            {
                sum2=sum2+11;
            }
            sum=sum1+sum2;
            if(sum>max&&sum<=21)
            {
                max=sum;
            }
        }
        if(max==0)
            max=sum;
    }
    if(count==2)
    {
        for(i=0;i<2;i++)
        {
            sum2=0;
            if(i==0)
                sum2=sum2+1;
            if(i==1)
                sum2=sum2+11;
            sum21=sum2;
            for(j=0;j<2;j++)
            {
                sum2=sum21;
                if(j==0)
                    sum2=sum2+1;
                if(j==1)
                    sum2=sum2+11;
                sum=sum1+sum2;
                if(sum>max&&sum<=21)
                {
                    max=sum;
                }
            }
        }
        if(max==0)
            max=sum;
    }
    if(count==3)
    {
        for(i=0;i<2;i++)
        {
            sum2=0;
            if(i==0)
                sum2=sum2+1;
            if(i==1)
                sum2=sum2+11;
            sum21=sum2;
            for(j=0;j<2;j++)
            {
                sum2=sum21;
                if(j==0)
                    sum2=sum2+1;
                if(j==1)
                    sum2=sum2+11;
                sum22=sum2;
                for(k=0;k<2;k++)
                {
                    sum2=sum22;
                    if(k==0)
                        sum2=sum2+1;
                    if(k==1)
                        sum2=sum2+11;
                    sum=sum1+sum2;
                    if(sum>max&&sum<=21)
                    {
                        max=sum;
                    }
                }
            }
        }
        if(max==0)
            max=sum;
    }
    if(count==4)
    {
        for(i=0;i<2;i++)
        {
            sum2=0;
            if(i==0)
                sum2=sum2+1;
            if(i==1)
                sum2=sum2+11;
            sum21=sum2;
            for(j=0;j<2;j++)
            {
                sum2=sum21;
                if(j==0)
                    sum2=sum2+1;
                if(j==1)
                    sum2=sum2+11;
                sum22=sum2;
                for(k=0;k<2;k++)
                {
                    sum2=sum22;
                    if(k==0)
                        sum2=sum2+1;
                    if(k==1)
                        sum2=sum2+11;
                    sum23=sum2;
                    for(l=0;l<2;l++)
                    {
                        sum2=sum23;
                        if(l==0)
                            sum2=sum2+1;
                        if(l==1)
                            sum2=sum2+11;
                        sum=sum1+sum2;
                        if(sum>max&&sum<=21)
                        {
                            max=sum;
                        }
                    }
                }
            }
        }
        if(max==0)
            max=sum;
    }

    if(count!=0)
    {   return max;}
    else
    {   return sum1;}
}
void main()
{
  int ph[10]={90,40,70,10};
  int qq=0;
  qq=sum(ph);
  printf("%d",qq);
  getch();
}

